name: minhhai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Lưu thông tin user đơn giản
  shared_preferences: ^2.2.2

  # Icon iOS
  cupertino_icons: ^1.0.8

  # SQLite Database
  sqflite: ^2.3.0
  path: ^1.8.0
  path_provider: ^2.1.5

  # Phát nhạc
  audioplayers: ^6.0.0

  # Xuất PDF
  pdf: ^3.11.0

  # tải file lên
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Tài nguyên ảnh & nhạc
  assets:
    - assets/images/
    - assets/music/
